// Team member names for the random recipient generator
// Add your team members' names here, one per line

export const TEAM_NAMES = [
    "Krishna Sistla",
    "Sarah Halverson",
    "Olena Kosinska",
    "Alin Luca",
    "Liz Holz ",
    "Hadley Robin",
    "Mausam Jain",
    "Paresh Joshi",
    "Max (Lucian Maxim)",
    "Chris Dollar",
    "Colin Reilly",
    "Robb Anderson",
    "Aimee Sher",
    "Andreea Ene",
    "Carl Schultze",
    "Casandra Cretu",
    "Andrei Clodius",
    "Codin Andrei",
    "David B. Anthony",
    "Gabriela Mitrana",
    "Haidy Perez-Francis",
    "Heather Barranco",
    "Jeffin Philip",
    "Kamila Triplett",
    "Mihai Bozgan",
    "Nataliia Zasoba",
    "Paul Boulescu",
    "Peter Vachon",
    "Prabhat Kumar",
    "Lance Garcia",
    "Satiswar Dash",
    "Shelley Dignum",
    "Vlad Constantinescu",
];


